const appLocaleData = require('react-intl/locale-data/zh');


module.exports = {
  locale: 'zh-CN',
  data: appLocaleData,
  messages: {
    'app.home.introduce': '一个服务于企业级产品的设计体系。基于『确定』和『自然』的设计价值观，通过模块化的解决方案，让设计者专注于 “更好的用户体验“。',
    'app.home.design-language': '设计语言',
    'app.home.solution': '解决方案',
    'app.home.components-explain': '基于 Ant Design 设计语言，我们提供了一套开箱即用的高质量 React 组件，用于开发和服务于企业级中后台产品，除官方的 React 实现，还有 Angular、Vue 的实现',
    'app.home.product-pro-slogan': '开箱即用的中台前端/设计解决方案',
    'app.home.product-mobile-slogan': 'antd-mobile 是 Ant Design 的移动规范的 React 实现',
    'app.home.product-antv-slogan': '简单、专业、拥有无限可能的数据可视化解决方案',
    'app.home.tool-package-title': 'Ant Design 资源包',
    'app.home.tool-package-content': 'Ant Design 相关设计资源下载',
    'app.home.tool-library-title': 'AntD Library',
    'app.home.tool-library-content': '一套精美得像视觉稿的 Axure 组件库',
    'app.home.tool-kitchen-title': 'Kitchen(敬请期待)',
    'app.home.tool-kitchen-content': '一个为设计师提效的 Sketch 工具集',
    'app.footer.repo': 'GitHub 仓库',
    'app.footer.awesome': 'Awesome Ant Design',
    'app.footer.chinamirror': '国内镜像站点 🇨🇳',
    'app.footer.primary-color-changed': '修改主题色成功！',
    'app.footer.scaffold': '脚手架',
    'app.footer.scaffolds': '脚手架市场',
    'app.footer.dev-tools': '开发工具',
    'app.footer.dva': '应用框架',
    'app.footer.resources': '资源链接',
    'app.footer.data-vis': '数据可视化',
    'app.footer.eggjs': '企业级 Node 开发框架',
    'app.footer.motion': '设计动效',
    'app.footer.antd-library': 'Axure 部件库',
    'app.footer.design-platform': '蚂蚁金服设计平台',
    'app.footer.antux': '页面逻辑素材',
    'app.footer.community': '社区',
    'app.footer.change-log': '更新记录',
    'app.footer.faq': '常见问题',
    'app.footer.feedback': '反馈和建议',
    'app.footer.stackoverflow': 'StackOverflow',
    'app.footer.segmentfault': 'SegmentFault',
    'app.footer.discuss-en': '在线讨论 (English)',
    'app.footer.discuss-cn': '在线讨论 (中文)',
    'app.footer.bug-report': '报告 Bug',
    'app.footer.issues': '讨论列表',
    'app.footer.version': '文档版本：',
    'app.footer.author': '蚂蚁金服体验技术部出品 @ AFX',
    'app.footer.work_with_us': '加入我们',
    'app.footer.more-product': '更多产品',
    'app.footer.privacy': '隐私权政策',
    'app.footer.commitment': '权益保障承诺书',
    'app.footer.company': '蚂蚁金融服务集团',
    'app.footer.ant-design': '蚂蚁 UI 体系',
  },
};
